export const elements = {
  imageInput: document.getElementById('imageInput'),
  clearBtn: document.getElementById('clearBtn'),
  aspectInput: document.getElementById('aspectInput'),
  transparentBgInput: document.getElementById('transparentBgInput'),
  imagePosInput: document.getElementById('imagePosInput'),
  layoutSelect: document.getElementById('layoutSelect'),
  headerTitle: document.getElementById('headerTitle'),
  headerSub: document.getElementById('headerSub'),
  trackInputs: document.querySelectorAll('.track-input'),
  widthInput: document.getElementById('widthInput'),
  widthVal: document.getElementById('widthVal'),
  contrastInput: document.getElementById('contrastInput'),
  contrastVal: document.getElementById('contrastVal'),
  brightnessInput: document.getElementById('brightnessInput'),
  brightVal: document.getElementById('brightVal'),
  ditherInput: document.getElementById('ditherInput'),
  paletteInput: document.getElementById('paletteInput'),
  transparencyInput: document.getElementById('transparencyInput'),
  dropoutsInput: document.getElementById('dropoutsInput'),
  dropoutsVal: document.getElementById('dropoutsVal'),
  tearInput: document.getElementById('tearInput'),
  resetBtn: document.getElementById('resetBtn'),
  downloadBtn: document.getElementById('downloadBtn'),
  canvas: document.getElementById('receiptCanvas'),
  
  ditherScaleInput: document.getElementById('ditherScaleInput'),
  ditherScaleVal: document.getElementById('ditherScaleVal'),

  modeSelect : document.getElementById('modeSelect'),
  colorModeSelect : document.getElementById('colorModeSelect'),
};
